<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p</name>
   <tag></tag>
   <elementGuidId>b184afb1-bfd1-4833-9500-86739f0939fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='tinymce']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>63f1faf6-f1bf-4dd9-95cc-baf8785f4539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tinymce&quot;)/p[1]</value>
      <webElementGuid>b5dda0cd-c1ed-48c5-9ccc-c238fad9f120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Add a new product attribute  nopCommer_25a275/iframe_System Font_Description_ifr</value>
      <webElementGuid>2b698672-3b06-46f3-87cf-b4d0395b8d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='tinymce']/p</value>
      <webElementGuid>0e83681e-f7e0-4683-aecc-8405f113662f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>7a92d302-28f8-4f95-9a3d-2dd0500fd822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
