<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip</name>
   <tag></tag>
   <elementGuidId>ca2dce25-734c-4f5a-a26f-6ad4db8cd1e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='recaptcha-verify-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-verify-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd3b7d89-f706-4546-b4f6-f66621b0b80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-button-default goog-inline-block</value>
      <webElementGuid>eb874315-43bd-4ec3-84e3-a9eacd97151f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-verify-button</value>
      <webElementGuid>2ea5ad58-458f-4a80-a2b4-92fb29e7aae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cca3642a-f64e-43c1-8f39-2012190e73d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>d48cc6d9-14fb-4625-ba39-bee21de03c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-verify-button&quot;)</value>
      <webElementGuid>1c9d350e-fdf5-4b23-ad6d-e6c50e4f7c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Contact  Hamsol Solution/iframe_Greatest_c-8efsd7dkc3pp</value>
      <webElementGuid>aba43a0a-91b3-45ab-991c-c43b5f9571b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='recaptcha-verify-button']</value>
      <webElementGuid>9ff6ffe0-b360-4c08-b461-c562f5acdd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect']/div[3]/div[2]/div/div[2]/button</value>
      <webElementGuid>a3ef62af-0d06-47d3-96e8-0b48f3a16139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='traffic lights'])[1]/following::button[6]</value>
      <webElementGuid>246fefc7-b7e1-4fb1-8161-66887b0b824b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'recaptcha-verify-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>930e1d87-2f38-40a2-975c-43340b0836b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skip']/parent::*</value>
      <webElementGuid>66064696-25d5-4b65-85c9-8f2874970c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>ee151d38-efaf-439e-8094-5361931534ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'recaptcha-verify-button' and (text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>bc95e3cc-51b2-4578-b149-9d6363942979</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
