<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Greatest_c-8efsd7dkc3pp</name>
   <tag></tag>
   <elementGuidId>39a19bb6-7e2c-4ef0-8ce1-e5d3df2edfc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-8efsd7dkc3pp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b5d4d1eb-e15c-43e3-9dc6-fa07aa1c1f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>9a1d2337-ddb0-4f5b-9745-3949d14c0a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=vpEprwpCoBMgy-fvZET0Mz6L&amp;k=6Ld8KDYUAAAAAL7iGk2islHZzNF01jDRXmFITIz0</value>
      <webElementGuid>8313e16d-91c1-4032-af1f-53d0a5082cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-8efsd7dkc3pp</value>
      <webElementGuid>b2b8630a-b8c3-4e7e-9b2c-83ad9cca11ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c74deb28-f238-432e-960a-74f2de5d0c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c41b2a98-265b-408f-93c6-3ba4a20ba4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>42f1ebe2-76e3-42c6-bec2-9d42b82c19c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;page-template-default page page-id-6&quot;]/div[3]/div[4]/iframe[1]</value>
      <webElementGuid>9dc1c3be-2bec-464b-a561-9cea34a04b94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-8efsd7dkc3pp']</value>
      <webElementGuid>85aea76b-8774-4146-aa6e-87d86ef76bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>cc20dc91-af70-4bdd-a2f9-4c5ef14dab26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=vpEprwpCoBMgy-fvZET0Mz6L&amp;k=6Ld8KDYUAAAAAL7iGk2islHZzNF01jDRXmFITIz0' and @name = 'c-8efsd7dkc3pp']</value>
      <webElementGuid>6d2aa656-f513-4750-8f59-7da7b118d52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
