<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact</name>
   <tag></tag>
   <elementGuidId>30e14e42-87b9-4311-82c5-b6cab1b567b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-primary-menu-1 > li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-24.last > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-primary-menu-1']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df2bb467-0f4c-49cc-b8f3-65ad71f6348b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hamsol.com/contact-us/</value>
      <webElementGuid>2333aa90-5daf-4367-b8de-aeff8903eae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact</value>
      <webElementGuid>3b140cc1-314a-4191-a34d-7263106bd554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-primary-menu-1&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-24 last&quot;]/a[1]</value>
      <webElementGuid>75f8e05b-8d35-43f3-a26b-574b66ffb7d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-primary-menu-1']/li[5]/a</value>
      <webElementGuid>2c1a41c3-c9f1-4c79-a36e-6dab1017fe77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Contact')])[2]</value>
      <webElementGuid>2212564c-19d1-4643-aab8-10dbb72cb4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[2]/following::a[1]</value>
      <webElementGuid>c42d13ad-0e68-4004-859f-9bceb3d55804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[2]/following::a[2]</value>
      <webElementGuid>4d258634-c5a9-4538-afc1-d3eaddfbaa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Info'])[1]/preceding::a[1]</value>
      <webElementGuid>aaa1fb16-8139-4fd4-aaca-e34e5920f563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://hamsol.com/contact-us/')])[2]</value>
      <webElementGuid>883e43bf-f8bf-4333-b225-43628e06e3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/ul/li[5]/a</value>
      <webElementGuid>d5e8a8d8-693b-48d8-9359-4c69011bc84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hamsol.com/contact-us/' and (text() = 'Contact' or . = 'Contact')]</value>
      <webElementGuid>c9bdb826-25f0-42c5-a73e-f587d8df548c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
