<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , f9rqr0rt2sj81679635628_7dac56</name>
   <tag></tag>
   <elementGuidId>35d05f11-8ab3-4961-b809-d5444ce8b96e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#f9rqr0rt2sj81679635628667</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='f9rqr0rt2sj81679635628667']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9bbe8494-8a6d-4964-8463-d69d7d6bf14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>e1e9b86e-4c79-4e96-a25b-5ea060bb5c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5a51c57-39a1-4c56-8533-f91234dd02b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>294ec3f6-0821-4739-99ae-fc98bd79282e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>64px</value>
      <webElementGuid>9a86e425-e781-45a7-ba3f-fe727b8c7597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>60px</value>
      <webElementGuid>de1a4e1c-616e-44ef-8d2d-109706bb0455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>f9rqr0rt2sj81679635628667</value>
      <webElementGuid>03adb90e-1429-430e-b894-8701b0d3f48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>chat widget</value>
      <webElementGuid>1177b7d1-1a3f-43cb-8915-8a48e0b20cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;f9rqr0rt2sj81679635628667&quot;)</value>
      <webElementGuid>7af766ea-d86c-402c-9633-e4b33e818bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='f9rqr0rt2sj81679635628667']</value>
      <webElementGuid>afe80146-30b9-44cd-a07f-c4598c2324f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='m7bijp50eps81679635628635']/iframe</value>
      <webElementGuid>2f256e6c-8672-494a-b99f-5c480f663339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/iframe</value>
      <webElementGuid>a15e71e8-ba07-4a85-987a-18ab416aeb80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'about:blank' and @id = 'f9rqr0rt2sj81679635628667' and @title = 'chat widget']</value>
      <webElementGuid>5d88989d-5402-4fa2-9ce0-57f3cab89c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
