<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_WebDriver.Window</name>
   <tag></tag>
   <elementGuidId>0b13a0bc-d532-4c77-a833-9f9e0a19d878</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriver.Timeouts'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(18) > a[title=&quot;interface in org.openqa.selenium&quot;] > span.interfaceName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>66a4fe3d-91f5-45fe-8463-1c1c9933f2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>interfaceName</value>
      <webElementGuid>0525d85f-3a53-4e6a-987a-305ce51a4f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WebDriver.Window</value>
      <webElementGuid>4d4a07cf-996b-4934-8263-a5029270be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[1]/ul[1]/li[18]/a[1]/span[@class=&quot;interfaceName&quot;]</value>
      <webElementGuid>220f7b72-1f4a-4620-99b9-64aba0680d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_By.Remotable/iframe_packageFrame</value>
      <webElementGuid>d45b4baa-8b9d-4ce3-b4d7-becbc363f4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriver.Timeouts'])[1]/following::span[1]</value>
      <webElementGuid>e84fbbc8-2b69-413f-abdc-8a79b3ed3680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriver.TargetLocator'])[1]/following::span[2]</value>
      <webElementGuid>ac8504ff-dd69-497b-ad7f-bb44183bad9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriverInfo'])[1]/preceding::span[1]</value>
      <webElementGuid>3ffb4ce8-e57b-42e3-ae07-f2960a11d0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebElement'])[1]/preceding::span[2]</value>
      <webElementGuid>453ff884-21a8-4c06-800e-122e987aa1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WebDriver.Window']/parent::*</value>
      <webElementGuid>00dc5017-bfa0-4fc1-8c76-af0cac71b805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[18]/a/span</value>
      <webElementGuid>33b98c3d-5230-47f5-95ea-7f9970c6262e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'WebDriver.Window' or . = 'WebDriver.Window')]</value>
      <webElementGuid>ab9bf9d3-1555-4a16-ae44-74c7a7e47a4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
